<div class="jumbotron">
    <h1>Bienvenue au jeu de cartes <span class="red">Cartoo</span></h1>

    <p>
        Pour commencer cliquer sur le bouton [Jouer] en bas pour tirer vos cartes.
       
    </p>
    <br/>
    <p style="text-align: center;"><a class="btn btn-danger btn-lg" href="javascript:return false;" id="playButton">Jouer</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-success btn-lg" href="javascript:return false;" id="checkButton">Valider</a></p>
</div>

<div style="margin-bottom: 20px;" id="serverResponse">

</div>

<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Vos cartes :</h3>
    </div>
</div>
<div class="row" id="cardsList">

    
    
</div>
<div id='ajaxLoader' style='width: 90%; top: 50%; text-align: center; position: fixed; display: none;'>
   <img src='img/ajax-loader.gif' alt='Loading' style=" background-color: white" />
</div>